name: kupprod
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./backend/env/.env.deploy
  db:
    image: "postgres:17"
    restart: always
    env_file:
      - ./backend/env/.env.deploy
    # volumes:
    #   - postgres_data:${PGDATA}
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
